include:
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.base.yaml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.build.yaml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.scan.yaml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.release.yaml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.release-google.yaml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.release-docker-io.yaml'
