name: Release to Docker Registries
on:
  repository_dispatch:
    types: [image-built]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Tag semver releases
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: ${{ github.event.client_payload.tag_latest }}

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: ${{ github.event.client_payload.image_name }}
          target_registry_username: github
          target_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/

      - name: Publish release to docker.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: ${{ github.event.client_payload.tag_latest }}

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: flownative/base
          target_registry_username: ${{ secrets.DOCKER_IO_REGISTRY_USER }}
          target_registry_password: ${{ secrets.DOCKER_IO_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://index.docker.io/v1/
