name: Release latest version
on:
  repository_dispatch:
    types: [image-built]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Tag semver releases
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: 'yes'

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: ${{ github.event.client_payload.image_name }}
          target_registry_username: github
          target_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/

      - name: Publish release to gcr.io (beach-core)
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: 'yes'

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: eu.gcr.io/flownative-beach/base
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://eu.gcr.io/v2/

      - name: Publish release to gcr.io (beach-a7c8b2)
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: 'yes'

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: eu.gcr.io/flownative-beach-a7c8b2/base
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_REGISTRY_PASSWORD_A7C8B2 }}
          target_registry_endpoint: https://eu.gcr.io/v2/

      - name: Publish release to docker.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: 'yes'

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: flownative/base
          target_registry_username: ${{ secrets.DOCKER_IO_REGISTRY_USER }}
          target_registry_password: ${{ secrets.DOCKER_IO_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://index.docker.io/v1/
