name: Build and release Docker images
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: flownative/action-docker-build@v1
        with:
          tag_ref: ${{ github.ref }}
          git_repository_url: https://github.com/${{ github.repository }}
          git_sha: ${{ github.sha }}
          image_name: flownative/docker-base/base
          registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Tag semver releases
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: 'yes'

          source_image_name: docker.pkg.github.com/flownative/docker-base/base
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: docker.pkg.github.com/flownative/docker-base/base
          target_registry_username: github
          target_registry_password: ${{ secrets.GITHUB_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/
